export const GENRES: string[] = [
  'Action',
  'Adventure',
  'Alternate History',
  'Anthology',
  'Apocalyptic',
  'Art',
  'Autobiography',
  'Biography',
  'Biographical Fiction',
  'Business',
  'Chick Lit',
  "Children's",
  'Christian Fiction',
  'Classics',
  'Climate Fiction',
  'Comedy',
  'Coming-of-age',
  'Contemporary Romance',
  'Cookbooks',
  'Crime',
  'Creative Nonfiction',
  'Dark Fantasy',
  'Detective',
  'Drama',
  'Dystopian',
  'Education',
  'Essay',
  'Fairy Tale',
  'Fantasy',
  'Folklore',
  'Graphic Novel',
  'Health',
  'Historical Fiction',
  'Historical Romance',
  'History',
  'Horror',
  'Humor',
  'Inspirational',
  'Legal Thriller',
  'Literary Fiction',
  'Magic Realism',
  'Memoir',
  'Military',
  'Military Sci-Fi',
  'Mystery',
  'Mythology',
  'Nature',
  'Noir',
  'Non-fiction',
  'Paranormal',
  'Paranormal Romance',
  'Philosophy',
  'Poetry',
  'Police Procedural',
  'Political',
  'Post-Apocalyptic',
  'Psychology',
  'Reference',
  'Regency',
  'Religion',
  'Romance',
  'Satire',
  'Science',
  'Science Fiction',
  'Self-Help',
  'Short Stories',
  'Social',
  'Space Opera',
  'Spy/Espionage',
  'Steampunk',
  'Suspense',
  'Thriller',
  'Travel',
  'True Crime',
  'Urban Fantasy',
  'Utopian',
  'Vampire',
  'Western',
  "Women's Fiction",
  'Young Adult',
];
